# Generated by Django 2.2.13 on 2020-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEnviron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('recTime', models.DateTimeField()),
                ('tem_in_loc1', models.FloatField()),
                ('hum_in_loc1', models.FloatField()),
                ('tem_coil_loc1', models.FloatField()),
                ('tem_in_loc2', models.FloatField()),
                ('hum_in_loc2', models.FloatField()),
                ('tem_coil_loc2', models.FloatField()),
                ('tem_in_loc3', models.FloatField()),
                ('hum_in_loc3', models.FloatField()),
                ('tem_coil_loc3', models.FloatField()),
                ('tem_out_loc1', models.FloatField()),
                ('hum_out_loc1', models.FloatField()),
                ('cond_loc1', models.BooleanField()),
                ('cond_loc2', models.BooleanField()),
                ('cond_loc3', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('forecast', models.CharField(choices=[('24', '24'), ('48', '48')], max_length=2)),
                ('recTime', models.DateTimeField()),
                ('tem_in_loc1', models.FloatField()),
                ('hum_in_loc1', models.FloatField()),
                ('tem_coil_loc1', models.FloatField()),
                ('tem_in_loc2', models.FloatField()),
                ('hum_in_loc2', models.FloatField()),
                ('tem_coil_loc2', models.FloatField()),
                ('tem_in_loc3', models.FloatField()),
                ('hum_in_loc3', models.FloatField()),
                ('tem_coil_loc3', models.FloatField()),
                ('tem_out_loc1', models.FloatField()),
                ('hum_out_loc1', models.FloatField()),
                ('cond_loc1', models.BooleanField()),
                ('cond_loc2', models.BooleanField()),
                ('cond_loc3', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcTime', models.DateTimeField()),
                ('temp_25', models.FloatField()),
                ('temp_46', models.FloatField()),
                ('humid_25', models.FloatField()),
                ('humid_46', models.FloatField()),
                ('rain_25', models.FloatField()),
                ('rain_46', models.FloatField()),
                ('wind_25', models.FloatField()),
                ('wind_46', models.FloatField()),
            ],
        ),
    ]
