# Generated by Django 2.2.13 on 2020-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEnviron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('recTime', models.DateTimeField()),
                ('tem_in_loc1', models.FloatField()),
                ('hum_in_loc1', models.FloatField()),
                ('tem_coil_loc1', models.FloatField()),
                ('tem_in_loc2', models.FloatField()),
                ('hum_in_loc2', models.FloatField()),
                ('tem_coil_loc2', models.FloatField()),
                ('tem_in_loc3', models.FloatField()),
                ('hum_in_loc3', models.FloatField()),
                ('tem_coil_loc3', models.FloatField()),
                ('tem_out_loc1', models.FloatField()),
                ('hum_out_loc1', models.FloatField()),
                ('cond_loc1', models.BooleanField()),
                ('cond_loc2', models.BooleanField()),
                ('cond_loc3', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('forecast', models.CharField(choices=[('24', '24'), ('48', '48')], max_length=2)),
                ('recTime', models.DateTimeField()),
                ('tem_in_loc1', models.FloatField()),
                ('hum_in_loc1', models.FloatField()),
                ('tem_coil_loc1', models.FloatField()),
                ('tem_in_loc2', models.FloatField()),
                ('hum_in_loc2', models.FloatField()),
                ('tem_coil_loc2', models.FloatField()),
                ('tem_in_loc3', models.FloatField()),
                ('hum_in_loc3', models.FloatField()),
                ('tem_coil_loc3', models.FloatField()),
                ('tem_out_loc1', models.FloatField()),
                ('hum_out_loc1', models.FloatField()),
                ('cond_loc1', models.BooleanField()),
                ('cond_loc2', models.BooleanField()),
                ('cond_loc3', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='PlantOneEnviron',
        ),
        migrations.DeleteModel(
            name='PlantTwoEnviron',
        ),
        migrations.DeleteModel(
            name='Prediction24',
        ),
        migrations.DeleteModel(
            name='Prediction48',
        ),
    ]
